nginx:
    build: build/nginx
    environment:
        - SYMFONY_ENV=local
        - APP_SITE_NAME=flosports
        - SYMFONY_DEBUG=1
        - NGINX_HOST=admin.flosports.local
        - NGINX_PORT=80
    ports:
        - "8080:80"
    links:
        - php
        - redis
    volumes:
        - ../flosports-cms:/app
redis:
    build: build/redis
    volumes:
        - ./data/redis:/var/lib/mysql
    ports:
        - "6380:6379"
db:
    image: mysql:5.7
    ports:
        - "3307:3306"
    environment:
        MYSQL_DATABASE: FloSports
        MYSQL_USER: flosports
        MYSQL_PASSWORD: flosports
        MYSQL_ROOT_PASSWORD: flosports
    volumes:
        - ./data/mysql:/var/lib/mysql
php:
    build: build/php
    environment:
        - APP_SITE_NAME=flosports
    volumes:
        - ../flosports-cms:/app
    working_dir: /app
    links:
        - db
        - redis