#
application:
    build: build/application
    volumes:
        - ../symfony-php:/app
        - ./data/redis:/var/lib/redis
        - ./data/mysql:/var/lib/mysql
php:
    build: build/php
    environment:
        - APP_SITE_NAME=flosports
    volumes_from:
        - application
    working_dir: /app
    links:
        - db
        - redis

db:
    image: mysql:5.7
    ports:
        - "3307:3306"
    environment:
        MYSQL_DATABASE: FloSports
        MYSQL_USER: flosports
        MYSQL_PASSWORD: flosports
        MYSQL_ROOT_PASSWORD: flosports
    volumes_from:
        - application

redis:
    build: build/redis
    volumes_from:
        - application
    ports:
        - "6380:6379"

nginx:
    build: build/nginx
    environment:
        - SYMFONY_ENV=local
        - APP_SITE_NAME=flosports
        - SYMFONY_DEBUG=1
        - NGINX_HOST=admin.flosports.local
        - NGINX_PORT=80
    ports:
        - "8080:80"
    links:
        - php
        - redis
    volumes_from:
        - application
